services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:25.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: dpg-csfmong8fa8c73a0kmrg-a
      DB_DATABASE: keycloak_db_z5z2
      DB_USER: keycloak_db_z5z2_user
      DB_PASSWORD: 6doCqHY6oxbUFxFpoEbXvSj2T3WzClLK
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/