server:
  port: 8081
  servlet:
    context-path: /course
spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://admin:7Fu8C1gbpjNMY9PQ@cluster0.fb5e0r9.mongodb.net/course-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bugbuster.click/realms/sunny

  redis:
    host: elearning.redis.cache.windows.net
    port: 6380
    password: ""
    ssl: true

  cloud:
    azure:
      storage:
        account-name: sunnystorage855
        account-key: jAZ/U552yytV/lE26idYXNq5OUCn7809visvtDfPbH9lTZ3Jbi571NNVPp1vDMp2ebx+8g9U7lb++AStf/LKGA==

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 510MB

idp:
  url: https://bugbuster.click
  client-id: sunny_app
  client-secret: p1q9lg1SZD2IoSSxD4EyuFYMGNQ735MJ

azure:
  blob:
    video-container: video-lesson-container
    doc-container: doc-lesson-container
    thumbnail-container: thumbnail-container

logging:
  level:
    org:
      springframework:
        cache: DEBUG

user-service:
  url: http://localhost:8080/user