server:
  port: 8085
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${PAYMENT_DB_URL}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: ${KAFKA_CONNECT}

    consumer:
      group-id: "payment-consumer-group"
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sunny.microservices.basedomain.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

payment:
  vnpay:
    tmn-code: ${PAYMENT_TMN_CODE}
    secret-key: ${PAYMENT_SECRET_KEY}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${RETURN_URL}
    timeout: 30