server:
  port: 8085
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb+srv://admin:7Fu8C1gbpjNMY9PQ@cluster0.fb5e0r9.mongodb.net/payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bugbuster.click/realms/sunny

  kafka:
    bootstrap-servers: "edumanabo-event.servicebus.windows.net:9093"
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://edumanabo-event.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=5NTRRP13oNjjKdiuVdlODLnkcRU1dpQPx+AEhAr6HCU=\";"

    consumer:
      group-id: "payment-consumer-group"
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sunny.microservices.basedomain.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

payment:
  vnpay:
    tmn-code: TK0ZLBPY
    secret-key: CH6Y317AJ8285FNZXHEKFA3OYTOD0HHQ
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://payment-service.ambitiousbush-9297f82e.southeastasia.azurecontainerapps.io/payment/api/v1/payments/vnpay-callback
    timeout: 30