server:
  port: 8085
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb+srv://admin:7Fu8C1gbpjNMY9PQ@cluster0.fb5e0r9.mongodb.net/payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bugbuster.click/realms/sunny

payment:
  vnpay:
    tmn-code: TK0ZLBPY
    secret-key: CH6Y317AJ8285FNZXHEKFA3OYTOD0HHQ
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://dev.roninhub.com/order/%s/status
    timeout: 15