server:
  port: 8082
  servlet:
    context-path: /learning

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://admin:7Fu8C1gbpjNMY9PQ@cluster0.fb5e0r9.mongodb.net/learning-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bugbuster.click/realms/sunny

idp:
  url: https://bugbuster.click
  client-id: sunny_app
  client-secret: p1q9lg1SZD2IoSSxD4EyuFYMGNQ735MJ

course-service:
  url: http://localhost:8081/course/

